Remove typechecking, ignore paths with .lint-ignore, improve output

diff --git a/install/code-lint-clang b/install/code-lint-clang
--- a/install/code-lint-clang
+++ b/install/code-lint-clang
@@ -1,25 +1,37 @@
 #!/usr/bin/env bash
 
+echo "Running $(basename ${0}) ..."
+
 set -eo pipefail
 
 curl -LOJs https://raw.githubusercontent.com/seqsense/ros_style/master/.clang-format
+trap 'rm -f .clang-format' EXIT
 
-files_to_check=$(find . -type f -not -path '*/build/*' -name "*.cpp" -o -name "*.h" -o -name "*.hpp")
+paths_to_ignore=$(find . -type f -not -path '*/build/*' -name ".lint-ignore" | xargs dirname)
+
+find_command="find . -type f -not -path '*/build/*'"
+for path in ${paths_to_ignore}; do
+    find_command="${find_command} -not -path '${path}/*'"
+done
+find_command="${find_command} -name '*.cpp' -o -name '*.h' -o -name '*.hpp'"
+
+files_to_check=($(eval "${find_command}"))
 
 if [ -z "${files_to_check}" ]; then
-    echo "found 0 source file(s)"
-    echo "passed=true"
+    echo " - Found 0 source file(s)"
+    echo -e " - [\e[32mPASSED\e[0m]"
     exit 0
 fi
 (
+    echo " - Found ${#files_to_check[@]} source file(s)"
     clang-format-11 \
         --style=file --Werror \
         ${files_to_check} \
         2>&1 >/dev/null |
         sed ':l; N; /\n\S\+:[0-9]\+:[0-9]\+: error: /b l; N; s/\n/%0A/g' |
         sed 's/^\([^:]\+\):\([0-9]\+\):\([0-9]\+\): error: \+\(.*\)/::error file=\1,line=\2,col=\3::\4/'
-) && echo "passed=true" ||
+) && echo -e " - [\e[32mPASSED\e[0m]" ||
     (
-        echo "passed=false"
+        echo -e " - [\e[31mFAILED\e[0m]"
         exit 1
     )
diff --git a/install/code-lint-flake8 b/install/code-lint-flake8
--- a/install/code-lint-flake8
+++ b/install/code-lint-flake8
@@ -1,26 +1,40 @@
 #!/usr/bin/env bash
 
+echo "Running $(basename ${0}) ..."
+
 curl -LOJs https://raw.githubusercontent.com/seqsense/ros_style/master/.flake8
 curl -LOJs https://raw.githubusercontent.com/seqsense/ros_style/master/pyproject.toml
+trap 'rm -f .flake8 pyproject.toml' EXIT
 
-files_to_check=$(find . -type f -not -path '*/\.git/*' -not -path '*/__pycache__/*' -not -path '*/\.mypy_cache/*')
+base_files_to_check=($(find . -type f -not -path '*/\.git/*' -not -path '*/__pycache__/*' -not -path '*/\.mypy_cache/*'))
 
-exit_code=0
-
-for file in ${files_to_check}; do
+files_to_check=()
+echo " - Scanning for python files by mimetype..."
+for file in ${base_files_to_check[@]}; do
     filetype=$(file -b --mime-type ${file})
     if echo ${filetype} | grep -qE "text/x-python|text/x-script.python"; then
-        echo "checking ${file}"
-        flake8 --count --show-source --statistics ${file} |
-            sed 's|^\(\S\+\):\([0-9]\+\):\([0-9]\+\): \(.*\)$|::error file=\1,line=\2,col=\3::\4\n\0|'
-        exit_code=$(($exit_code | ${PIPESTATUS[0]}))
+        files_to_check+=(${file})
     fi
 done
 
+if [ -z "${files_to_check}" ]; then
+    echo " - Found 0 source file(s)"
+    echo -e " - [\e[32mPASSED\e[0m]"
+    exit 0
+fi
+exit_code=0
+
+echo " - Found ${#files_to_check[@]} source file(s)"
+for file in ${files_to_check[@]}; do
+    flake8 --show-source --statistics ${file} |
+        sed 's|^\(\S\+\):\([0-9]\+\):\([0-9]\+\): \(.*\)$|::error file=\1,line=\2,col=\3::\4\n\0|'
+    exit_code=$(($exit_code | ${PIPESTATUS[0]}))
+done
+
 if [ ${exit_code} -eq 0 ]; then
-    echo "passed=true"
+    echo -e " - [\e[32mPASSED\e[0m]"
 else
-    echo "passed=false"
+    echo -e " - [\e[31mFAILED\e[0m]"
 fi
 
 exit ${exit_code}
diff --git a/install/code-lint-roslint b/install/code-lint-roslint
--- a/install/code-lint-roslint
+++ b/install/code-lint-roslint
@@ -1,22 +1,33 @@
 #!/usr/bin/env bash
 
+echo "Running $(basename ${0}) ..."
+
 set -eo pipefail
 
-files_to_check=$(find . -type f -not -path '*/build/*' -name "*.cpp" -o -name "*.h" -o -name "*.hpp")
+paths_to_ignore=$(find . -type f -not -path '*/build/*' -name ".lint-ignore" | xargs dirname)
+
+find_command="find . -type f -not -path '*/build/*'"
+for path in ${paths_to_ignore}; do
+    find_command="${find_command} -not -path '${path}/*'"
+done
+find_command="${find_command} -name '*.cpp' -o -name '*.h' -o -name '*.hpp'"
+
+files_to_check=($(eval "${find_command}"))
 
 if [ -z "${files_to_check}" ]; then
-    echo "found 0 source file(s)"
-    echo "passed=true"
+    echo " - Found 0 source file(s)"
+    echo -e " - [\e[32mPASSED\e[0m]"
     exit 0
 fi
 (
+    echo " - Found ${#files_to_check[@]} source file(s)"
     roslint-cpplint \
         --filter=-runtime/references,-build/c++11 --headers=h,hpp \
         ${files_to_check} \
         2>&1 >/dev/null |
         sed 's/^\([^:]\+\):\([0-9]\+\):\s\+\(.*\)/::error file=\1,line=\2::\3/'
-) && echo "passed=true" ||
+) && echo -e " - [\e[32mPASSED\e[0m]" ||
     (
-        echo "passed=false"
+        echo -e " - [\e[31mFAILED\e[0m]"
         exit 1
     )
diff --git a/install/code-lint-typecheck b/install/code-lint-typecheck
--- a/install/code-lint-typecheck
+++ b/install/code-lint-typecheck
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
 
+echo "Running $(basename ${0}) ..."
+
 set -eo pipefail
 
 curl -LOJs https://raw.githubusercontent.com/seqsense/ros_style/master/mypy.ini
+trap 'rm -f mypy.ini' EXIT
 
 cmd="mypy --config-file mypy.ini --scripts-are-modules"
 
@@ -16,10 +19,10 @@ for file in ${files_to_check}; do
         python_files+=(${file})
     fi
 done
-echo "found ${#python_files[@]} python file(s)"
 
+echo " - Found ${#python_files[@]} python file(s)"
 if [ ${#python_files[@]} -eq 0 ]; then
-    echo "passed=true"
+    echo -e " - [\e[32mPASSED\e[0m]"
     exit 0
 fi
 
@@ -41,9 +44,9 @@ echo "${output}" | sed -n 's|^\(\S\+\):\([0-9]\+\):\([0-9]\+\): error: \(.*\)$|:
 if [[ -n "$result" ]]; then
     error="$(echo $result | awk '/^Found/{print $2}')"
     if [[ -z "$error" ]]; then
-        echo "passed=true"
+        echo -e " - [\e[32mPASSED\e[0m]"
         exit 0
     fi
 fi
-echo "passed=false"
+echo -e " - [\e[31mFAILED\e[0m]"
 exit 1
