lint-sq-clang: Improve output formatting

diff --git a/install/lint-sq-clang b/install/lint-sq-clang
--- a/install/lint-sq-clang
+++ b/install/lint-sq-clang
@@ -23,14 +23,20 @@ if [ -z "${files_to_check}" ]; then
 fi
 (
     echo " - Found ${#files_to_check[@]} source file(s)"
-    clang-format-11 \
-        --style=file --Werror \
-        "${files_to_check[@]}" \
-        2>&1 >/dev/null |
-        sed ':l; N; /\n\S\+:[0-9]\+:[0-9]\+: error: /b l; N; s/\n/%0A/g' |
-        sed 's/^\([^:]\+\):\([0-9]\+\):\([0-9]\+\): error: \+\(.*\)/::error file=\1,line=\2,col=\3::\4/'
+    passed=true
+    for file in "${files_to_check[@]}"; do
+    if ! diff -q "$file" <(clang-format-11 --style=file --Werror "$file") 2>&1 >/dev/null; then
+        echo -e "\e[31mDIFFERENCES FOUND\e[0m in ${file}"
+        diff "$file" <(clang-format-11 --style=file --Werror "$file")
+        echo ""
+        echo "----"
+        echo ""
+        passed=false
+    fi
+    done
+    $passed
 ) && echo -e " - [\e[32mPASSED\e[0m]" ||
     (
-        echo -e " - [\e[31mFAILED\e[0m]"
+        echo -e " - [\e[31mFAILED\e[0m] Some file(s) require formatting"
         exit 1
     )
